ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 4000
    onOpen: ignore
    # making this public so that we can benefit from apollo studio
    visibility: public

tasks:
  - name: services
    before: npm i -g lerna nodemon
    init: lerna bootstrap
    command: lerna exec --parallel npm run start
  - name: NGINX
    command: gp await-port 3000 && nginx

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets
    - esbenp.prettier-vscode
    - graphql.vscode-graphql
    - dbaeumer.vscode-eslint
    - sdras.night-owl

image:
  file: .gitpod.Dockerfile
